export const ROUTES: string[] = [
  '/',
  '/list',
  '/calendar',
  '/embed/:id',
  '/event/:id',
  '/item/:id',
  '/film/:slug',
  '/interactive/:slug',
  '/audio/:slug',
  '/node/:slug',
  '/resource/:slug',
  '/awards',
  '/team',
  '/partners',
  '/terms-and-conditions',
  '/privacy-and-cookies',
  '/about',
  '/films',
  '/lesson plans',
  '/assembly scripts',
  '/interactive',
  '/me',
  '/me/lists',
  '/me/list/:id',
  '/rmcallback',
];
